org: brunocw
app: dailynews
service: dailynews-bot

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
plugins:
  - serverless-plugin-typescript

functions:
  postDailyTweet:
    handler: handler.run
    events:
      - schedule: cron(0 9 ? * MON-FRI *)